const EXCEPTION = "EXCEPTION";
const CLEAR_EXCEPTION_MSG = "CLEAR_EXCEPTION_MSG";
const SET_USER_ID = "SET_USER_ID";
const CLEAR_USER_ID = "CLEAR_USER_ID";
const SET_ORDER_DET_ID = "SET_ORDER_DET_ID";
const CLEAR_ORDER_DET_ID = "CLEAR_ORDER_DET_ID";
const SET_ORDER_LIST_ID = "SET_ORDER_LIST_ID";
const CLEAR_ORDER_LIST_ID = "CLEAR_ORDER_LIST_ID";

const Types = {
	exception: {
		EXCEPTION,
		CLEAR_EXCEPTION_MSG,
	},
	user: {
		SET_USER_ID,
		CLEAR_USER_ID,
	},
	order: {
		SET_ORDER_DET_ID,
		CLEAR_ORDER_DET_ID,
		SET_ORDER_LIST_ID,
		CLEAR_ORDER_LIST_ID,
	},
};

export default Types;
